---
keys:
  - &common age1nfa5tsvl33wmex09mj27kzcrl25xz5h74sg64rka2cekhjrd5frsnsymry
  - &geonosis age18eug2ah672kzv6nnj3kaljm3v7kxdufg7dga73c2vpupsd0nk3zs0jevgw
  - &tatooine age1qdev3fstezvtq3zyvxxdgneqy2v48whjak6pvqsk38eg30g74ecqz55c8m

creation_rules:
  - path_regex: homes/pigeonf/.+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *common
  - path_regex: systems/geonosis/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *geonosis
  - path_regex: systems/tatooine/secrets/.+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *tatooine
