version = 1

[[annotations]]
path = [
    ".dotter/**/*",
    ".editorconfig",
    ".gitignore",
    "atuin/**/*",
    "flake.lock",
    "flake.nix",
    "helix/**/*",
    "home-manager/**/*",
]
SPDX-FileCopyrightText = "Jonas Fierlings <fnoegip@gmail.com>"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "atuin/.config/atuin/themes/catppuccin-macchiato.toml"
]
SPDX-FileCopyrightText = "2021-present Catppuccin Org"
SPDX-License-Identifier = "MIT"
