[[language]]
name = "kdl"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "nix"
formatter = { command = "nixfmt" }

[[language]]
name = "sshclientconfig"
# https://github.com/helix-editor/helix/issues/6896
file-types = [
  { glob = ".ssh/config" },
  { glob = "/etc/ssh/ssh_config" },
  { glob = "ssh_config.d/*.conf" },
  { glob = ".ssh/*.d/*.conf" },
]

[[language]]
name = "yaml"
# https://github.com/helix-editor/helix/issues/6896
file-types = [
  "yml",
  "yaml",
  { glob = ".prettierrc" },
  { glob = ".clangd" },
  { glob = ".clang-format" },
  { glob = ".clang-tidy" },
  { glob = ".gem/credentials" },
  { glob = ".kube/config" },
  { glob = ".kube/kuberc" },
  { glob = "yarn.lock" },
  "winget",
  "sublime-syntax",
  { glob = "templates/*.yml" },
  { glob = "templates/*/template.yml" },
]

[[language]]
name = "ninja"
scope = "source.ninja"
injection-regex = "ninja"
file-types = ["ninja"]
indent = { tab-width = 4, unit = "    " }
comment-token = "#"

[[language]]
name = "rpmspec"
scope = "source.rpmspec"
injection-regex = "spec"
file-types = ["spec"]
indent = { tab-width = 4, unit = "    " }
comment-token = "#"

[language-server.yaml-language-server]
config = { yaml = { customTags = ["!reference sequence"] } }

[[grammar]]
name = "ninja"
source = { git = "https://github.com/alemuller/tree-sitter-ninja", rev = "0a95cfdc0745b6ae82f60d3a339b37f19b7b9267" }

[[grammar]]
name = "rpmspec"
source = { git = "https://github.com/shaba/tree-sitter-rpmspec", rev = "aa0a45a93caef9a1aeb47ab72502cd223ae0aecb" }
