---
global:
  CI: "true"
  CI_API_GRAPHQ_URL: https://gitlab.com/api/graphql
  CI_BUILDS_DIR: /gcl-builds
  CI_CONFIG_PATH: .gitlab-ci.yml
  CI_PIPELINE_SOURCE: "merge_request_event"
  CI_MERGE_REQUEST_TARGET_BRANCH_NAME: main
  CI_REGISTRY: registry.internal
  CI_REGISTRY_USER: gitlab-ci-token
  CI_REGISTRY_PASSWORD: <empty>
  GITLAB_USER_ID: 409429
  GITLAB_USER_LOGIN: PigeonF
