concurrent = 10
check_interval = 3
shutdown_timeout = 30

[[runners]]
name = "Default Runner"
url = "https://gitlab.com"
token = "@GLR_AUTHENTICATION_TOKEN@"
executor = "docker"
cache_dir = "/cache"
output_limit = 8192
environment = [
    # Make sure services can reach each other
    # "FF_NETWORK_PER_BUILD=1",
    # Make sure docker CLI can reach the dind service
    # "DOCKER_TLS_CERTDIR=/certs",
    # "DOCKER_CERT_PATH=/certs/client",
    # "DOCKER_TLS_VERIFY=1",
    # "DOCKER_HOST=tcp://docker:2376"
]
# pre_build_script = """
# : Runner specific cache setup
# if [[ -r /etc/nix/nix.conf ]]; then
#     # nix-env -iA nixpkgs.bashInteractive
#     echo "store = unix:///mnt/nix/var/nix/daemon-socket/socket?root=/mnt" >>/etc/nix/nix.conf
# fi
# """
# post_build_script = """
# if [[ -r /etc/nix/nix.conf ]]; then
#     for result in result*; do
#         nix --extra-experimental-features nix-command copy --to local --from unix:///mnt/nix/var/nix/daemon-socket/socket?root=/mnt --no-check-sigs "$(realpath "$result")"
#     done
# fi
# """

[runners.docker]
cache_dir = "/cache"
tls_verify = true
image = "busybox"
privileged = true
volumes = [
    # Cache directory used by gitlab-runner for build caches
    "/cache",
    # This is used to make the dind service work with TLS (since the TLS
    # certificates are generated by the dind service, and have to be imported
    # by the docker CLI.
    "/certs/client",
    # Directory where gitlab-runner stores the build folders by default
    "/builds",
    # Used for caching derivations on nixos/nix
    # "/nix:/mnt/nix:ro"
]
