concurrent = 10
check_interval = 3
shutdown_timeout = 30

[[runners]]
name = "Default Runner"
url = "https://gitlab.com"
token = "@GLR_AUTHENTICATION_TOKEN@"
executor = "docker"
cache_dir = "/cache"
output_limit = 8192

[runners.docker]
cache_dir = "/cache"
tls_verify = true
image = "busybox"
privileged = true
volumes = ["/certs/client", "/cache", "/builds", "/nix:/mnt/nix:ro"]
post_get_sources_script = """
if [[ -r /etc/nix/nix.conf ]]; then
    echo "store = unix:///mnt/nix/var/nix/daemon-socket/socket?root=/mnt" >>/etc/nix/nix.conf
fi
"""
