[misc]
assume_yes = true
ignore_failures = ["git_repos", "containers", "vagrant", "system"]
cleanup = true

[git]
repos = [
  "D:/git/github.com/PigeonF/*",
  "D:/git/gitlab.com/PigeonF/*",
  "D:/git/bitbucket.org/PigeonF/*",
  "D:/git/gitlab.kitware.com/PigeonF/*",
  "D:/git/codeberg.org/PigeonF/*",
]
