theme = "catppuccin_macchiato"

[editor]
cursorline = true
line-number = "relative"
rulers = [100, 120]
true-color = true
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
