# [language-server.harper]
# environment = { NO_COLOR = "1" }
# command = "harper-ls"
# args = ["--stdio"]

# [language-server.harper.config.harper-ls.linters]
# spaces = true

[language-server.typos]
command = "typos-lsp"
