[bat.files]
"bat/.config/" = "~/.config/"

[btop.files]
"btop/.config/" = "~/.config/"

[fd.files]
"fd/.config/" = "~/.config/"

[helix.files]
"helix/.config/" = "~/.config/"

[jujutsu.files]
"jujutsu/.config/" = "~/.config/"

[ripgrep.files]
"ripgrep/.config/" = "~/.config/"
