[alacritty.files]
"alacritty/.config/" = "~/.config/"

[alacritty.files."alacritty/.config/alacritty/linux.toml"]
target = "~/AppData/Roaming/alacritty/platform.toml"
type = "symbolic"

[atuin.files]
"atuin/.config/" = "~/.config/"

[bat.files]
"bat/.config/" = "~/.config/"

[btop.files]
"btop/.config/" = "~/.config/"

[eza.files]
"eza/.config/" = "~/.config/"

[fd.files]
"fd/.config/" = "~/.config/"

[git.files]
"git/.config/" = "~/.config/"

[git.files."git/.config/git/linux.gitconfig"]
target = "~/.config/git/platform.gitconfig"
type = "symbolic"

[helix.files]
"helix/.config/" = "~/.config/"

[jujutsu.files]
"jujutsu/.config/" = "~/.config/"

[powershell.files]
"powershell/.config/" = "~/.config/"

[ripgrep.files]
"ripgrep/.config/" = "~/.config/"

[starship.files]
"starship/.config/" = "~/.config/"

[yazi.files]
"yazi/.config/" = "~/.config/"

[zellij.files]
"zellij/.config/" = "~/.config/"
