[alacritty.files]
"alacritty/.config/" = "~/AppData/Roaming/"

[alacritty.files."alacritty/.config/alacritty/windows.toml"]
target = "~/AppData/Roaming/alacritty/platform.toml"
type = "symbolic"

[atuin.files]
"atuin/.config/" = "~/AppData/Roaming/"

[bat.files]
"bat/.config/" = "~/AppData/Roaming/"

[eza.files]
"eza/.config/" = "~/AppData/Roaming/"

[fd.files]
"fd/.config/" = "~/AppData/Roaming/"

[git.files]
"git/.config/" = "~/AppData/Roaming/"

[git.files."git/.config/git/windows.gitconfig"]
target = "~/AppData/Roaming/git/platform.gitconfig"
type = "symbolic"

[helix.files]
"helix/.config/" = "~/AppData/Roaming/"

[jujutsu.files]
"jujutsu/.config/" = "~/AppData/Roaming/"

[powershell.files]
"powershell/.config/powershell/" = "~/Documents/PowerShell/"

[ripgrep.files]
"ripgrep/.config/" = "~/AppData/Roaming/"

[spicetify.files]
"spicetify/.config/" = "~/AppData/Roaming/"
"spicetify/.config/spicetify/config-xpui.ini" = { target = "~/AppData/Roaming/spicetify/config-xpui.ini", type = "template" }

[starship.files]
"starship/.config/" = "~/AppData/Roaming/"

[topgrade.files]
"topgrade/.config/" = "~/AppData/Roaming/"

[yazi.files]
"yazi/.config/yazi/" = "~/AppData/Roaming/yazi/config/"
