[bat.files]
"bat/.config/" = "~/AppData/Roaming/"

[fd.files]
"fd/.config/" = "~/AppData/Roaming/"

[helix.files]
"helix/.config/" = "~/AppData/Roaming/"

[jujutsu.files]
"jujutsu/.config/" = "~/AppData/Roaming/"

[ripgrep.files]
"ripgrep/.config/" = "~/AppData/Roaming/"

[yazi.files]
"yazi/.config/yazi/" = "~/AppData/Roaming/yazi/config/"
