dialect = "uk"
update_check = false
history_filter = [
  "^cat",
  "^cd",
  "^exit",
  "^export [0-9a-zA-Z\\-_]+?[-_]TOKEN=",
  "^l[las]?$",
]
prefers_reduced_motion = true

[theme]
name = "catppuccin-macchiato"
