#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
email = "fnoegip@gmail.com"
name = "Jonas Fierlings"

[fsmonitor]
backend = "watchman"

[ui]
default-command = ["log", "-T", "log_oneline"]
diff-editor = ":builtin"
diff-formatter = ["difft", "--color=always", "$left", "$right"]
# merge-editor = "vscodium"
paginate = "never"
show-cryptographic-signatures = true

[git]
sign-on-push = true
private-commits = "private_commits()"

[signing]
behavior = "drop"
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID+2wAQrbFDe18oFY2Mv6qsUcYWJZPAcsV+Xr4ZHzncL"

[[--scope]]
--when.platforms = ["linux"]

[--scope.signing]
backends.ssh.allowed-signers = "~/.config/jj/allowed_signers"

[[--scope]]
--when.platforms = ["windows"]

[--scope.signing]
backends.ssh.allowed-signers = "~/AppData/Roaming/jj/allowed_signers"

[aliases]
d = ["diff"]
ds = ["diff", "--stat"]
dd = ["diff", "-r", "stack()"]
g = ["git"]
gp = ["git", "push"]
gpt = ["git", "push", "--tracked"]
gpc = ["git", "push", "-c"]
l = ["log", "-T", "builtin_log_oneline",  "-r", "stack(@)"]
ln = ["log", "-T", "builtin_log_oneline", "-r", "::@", "--limit"]
lall = ["log", "-T", "builtin_log_oneline", "-r", "::@"]
ll = ["log", "-T", "builtin_log_compact"]
ld = ["log", "-T", "builtin_log_detailed"]
lo = ["log", "-T", "builtin_log_oneline"]
ls = ["log", "-r", "mutable()::@"]
n = ["new", "trunk()"]
s = ["status"]
sq = ["squash"]
sqk = ["squash", "--keep-empty"]
restack = ["rebase", "--onto", "trunk()", "--source", "(roots(trunk()..) & mutable()) ~ (::bookmarks())", "--simplify-parents"]
prestack = ["rebase", "--onto", "trunk()", "--source", "roots(private_commits())", "--simplify-parents"]
stack = ["rebase", "--after", "trunk()", "--before", "closest_merge(@)", "--revision"]
stage = ["stack", "closest_merge(@)+:: ~ empty()"]
tug = ["bookmark", "advance"]

[revsets]
bookmark-advance-to = "@-"

[revset-aliases]
'at' = '@'
'stack()' = 'stack(@)'
'stack(x)' = '::x ~ ::trunk()'
"closest_merge(to)" = "heads(::to & merges())"
"private_commits()" = "description('wip:*') | description('private:*')"
"in_merge(x)" = "::x ~ ::first_parent(x)"

[templates]
log = "builtin_log_comfortable"
commit_trailers = '''
concat(
  format_signed_off_by_trailer(self),
)
'''
draft_commit_description = "builtin_draft_commit_description_with_diff"

[template-aliases]
starship = '''
separate(" ",
    change_id.shortest(6),
    bookmarks.map(|x| if(
        x.name().substr(0, 20).starts_with(x.name()),
        x.name().substr(0, 20),
        x.name().substr(0, 19) ++ "…")
    ).join(" "),
    if(
        description.first_line().substr(0, 24).starts_with(description.first_line()),
        description.first_line().substr(0, 24),
        description.first_line().substr(0, 23) ++ "…"
    ),
    if(conflict, "conflict"),
    if(divergent, "divergent"),
    if(hidden, "hidden"),
)
'''
log_oneline = 'log_oneline(self)'
'log_oneline(commit)' = '''
if(commit.root(),
  format_root_commit(commit),
  label(
    separate(" ",
      if(commit.current_working_copy(), "working_copy"),
      if(commit.immutable(), "immutable", "mutable"),
      if(commit.conflict(), "conflicted"),
    ),
    separate(" ",
      format_short_change_id_with_change_offset(commit),
      format_short_signature_oneline(commit.author()),
      format_timestamp(commit_timestamp(commit)),
      commit.bookmarks(),
      commit.tags(),
      commit.working_copies(),
      format_short_commit_id(commit.commit_id()),
      format_commit_labels(commit),
      if(config("ui.show-cryptographic-signatures").as_boolean(),
        format_short_cryptographic_signature(commit.signature())
      ),
      if(commit.empty(), empty_commit_marker),
      if(commit.description(),
        commit.description().first_line(),
        label(if(commit.empty(), "empty"), description_placeholder),
      ),
    ) ++ "\n",
  )
)
'''

[[--scope]]
--when.commands = ["diff", "show"]

[--scope.ui]
pager = "delta"
