#:schema https://raw.githubusercontent.com/jj-vcs/jj/main/cli/src/config-schema.json

[user]
email = "fnoegip@gmail.com"
name = "Jonas Fierlings"

[fsmonitor]
backend = "watchman"

[ui]
default-command = ["log", "-n", "10"]
# TODO(PigeonF): Figure out something cross platform.
diff-editor = ":builtin"
diff-formatter = ["difft", "--color=always", "$left", "$right"]
# merge-editor = "vscodium"
paginate = "never"
show-cryptographic-signatures = true

[git]
sign-on-push = true
private-commits = "description(glob:\"private:*\")"

[signing]
behavior = "drop"
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID+2wAQrbFDe18oFY2Mv6qsUcYWJZPAcsV+Xr4ZHzncL"

[[--scope]]
--when.platforms = ["linux"]

[--scope.signing]
backends.ssh.allowed-signers = "~/.config/jj/allowed_signers"

[[--scope]]
--when.platforms = ["windows"]

[--scope.signing]
backends.ssh.allowed-signers = "~/AppData/Roaming/jj/allowed_signers"

[aliases]
d = ["diff"]
ds = ["diff", "--stat"]
g = ["git"]
gp = ["git", "push"]
gpc = ["git", "push", "-c"]
gpt = ["git", "push", "--tracked"]
l = ["log", "-T", "builtin_log_compact"]
ll = ["log", "-T", "builtin_log_detailed"]
ls = ["log", "-r", "mutable()::@"]
restack = ["rebase", "--onto", "trunk()", "--source", "roots(trunk()..) & mutable()", "--simplify-parents"]
s = ["status"]
sq = ["squash"]
sqk = ["squash", "--keep-empty"]
stack = ["rebase", "--after", "trunk()", "--before", "closest_merge(@)", "--revision"]
stage = ["stack", "closest_merge(@)+:: ~ empty()"]
tug = ["bookmark", "advance"]

[revsets]
bookmark-advance-to = "@-"

[revset-aliases]
"closest_merge(to)" = "heads(::to & merges())"

[templates]
log = "builtin_log_comfortable"
commit_trailers = '''
concat(
  format_signed_off_by_trailer(self),
)
'''
draft_commit_description = "builtin_draft_commit_description_with_diff"

[template-aliases]
starship = '''
separate(" ",
    change_id.shortest(6),
    bookmarks.map(|x| if(
        x.name().substr(0, 20).starts_with(x.name()),
        x.name().substr(0, 20),
        x.name().substr(0, 19) ++ "…")
    ).join(" "),
    if(
        description.first_line().substr(0, 24).starts_with(description.first_line()),
        description.first_line().substr(0, 24),
        description.first_line().substr(0, 23) ++ "…"
    ),
    if(conflict, "conflict"),
    if(divergent, "divergent"),
    if(hidden, "hidden"),
)
'''

[[--scope]]
--when.commands = ["diff", "show"]

[--scope.ui]
pager = "delta"
