# Configuration for github.com

Host alpinelinux gitlab.alpinelinux gitlab.alpinelinux.org
    HostName gitlab.alpinelinux.org
    User git
    IdentityFile ~/.ssh/keys.d/pigeonf@gitlab.alpinelinux.org.pub
