# Configuration for homelab dev machine

Host hl-dev-01 hl-dev-01.internal hl-dev-01.fritz.box
    HostName hl-dev-01
    User developer
    IdentityFile ~/.ssh/keys.d/developer@hl-dev-01.pub
    ForwardAgent yes
    LocalForward localhost:3000 localhost:3000
    LocalForward localhost:8000 localhost:8000
    LocalForward localhost:8080 localhost:8080
