# Configuration for homelab dev machine

Host hl-dev-02 hl-dev-02.internal hl-dev-02.fritz.box
    HostName hl-dev-02
    User reviewer
    IdentityFile ~/.ssh/keys.d/reviewer@hl-dev-x-02
    ForwardAgent no
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    ProxyCommand ssh -T hl-vhost-x-01 systemd-vmspawn-ssh-proxy %h %p
