# Configuration for homelab dev machine

Host hl-dev-x-02 hl-dev-x-02.internal hl-dev-x-02.fritz.box
    HostName hl-dev-x-02
    User reviewer
    IdentityFile ~/.ssh/keys.d/developer@hl-dev-x-02.pub
    ForwardAgent no
