# Configuration for homelab virtual host

Host hl-svc-x-01 hl-svc-x-01.internal hl-svc-x-01.fritz.box
    HostName hl-svc-x-01
    User root
    IdentityFile ~/.ssh/keys.d/root@hl-svc-x-01.pub
    ForwardAgent No
