# Configuration for homelab virtual host

Host hl-svc-01 hl-svc-01.internal hl-svc-01.fritz.box
    HostName hl-svc-01
    User root
    IdentityFile ~/.ssh/keys.d/root@hl-svc-01.pub
    ForwardAgent No
