# Configuration for homelab virtual host

Host hl-svc-x-01 hl-svc-x-01.internal hl-svc-x-01.fritz.box
    HostName hl-svc-x-01
    User administrator
    IdentityFile ~/.ssh/keys.d/administrator@hl-svc-x-01.pub
    ForwardAgent yes
