# Configuration for homelab virtual host

Host hl-vhost-01 hl-vhost-01.internal hl-vhost-01.fritz.box
    HostName hl-vhost-01
    User administrator
    IdentityFile ~/.ssh/keys.d/administrator@hl-vhost-01.pub
    ForwardAgent yes
