# Configuration for homelab virtual host

Host hl-vhost-x-01 hl-vhost-x-01.internal hl-vhost-x-01.fritz.box
    HostName hl-vhost-x-01
    User administrator
    IdentityFile ~/.ssh/keys.d/administrator@hl-vhost-x-01.pub
    IdentityFile ~/.ssh/keys.d/root@hl-vhost-x-01.pub
