includes = [".dotter/windows.toml"]

packages = [
  "alacritty",
  "atuin",
  "bat",
  "bin",
  "erdtree",
  "git",
  "helix",
  "jj",
  "nushell",
  "nvim",
  "spicetify",
  "starship",
  "topgrade",
  "vscodium",
  "wezterm",
]
