[alacritty.files]
"dotfiles/alacritty/.config/alacritty/alacritty.toml" = "~/.config/alacritty/alacritty.toml"

[atuin.files]
"dotfiles/atuin/.config/atuin/config.toml" = "~/.config/atuin/config.toml"

[erdtree.files]
"dotfiles/erdtree/config.toml" = "~/.config/erdtree/.erdtree.toml"

[bash.files]
"dotfiles/bash/bash-preexec.sh" = "~/.config/bashrc.d/bash-preexec.sh"
"dotfiles/bash/bashrc" = { target = "~/.bashrc", type = "template" }
"dotfiles/bash/profile" = "~/.profile"
"dotfiles/bash/bash_profile" = "~/.bash_profile"

[git.files]
"dotfiles/git/gitconfig" = "~/.config/git/config"
"dotfiles/git/gitignore" = "~/.config/git/ignore"
"dotfiles/git/allowed_signers" = "~/.ssh/allowed_singers"

[starship.files]
"dotfiles/starship/starship.toml" = "~/.config/starship.toml"
