[alacritty.files]
"dotfiles/alacritty/.config/alacritty/alacritty.toml" = "~/.config/alacritty/alacritty.toml"

[atuin.files]
"dotfiles/atuin/.config/atuin/config.toml" = "~/.config/atuin/config.toml"

[bash.files]
"dotfiles/bash/.bash_profile" = "~/.bash_profile"
"dotfiles/bash/.bashrc" = { target = "~/.bashrc", type = "template" }
"dotfiles/bash/.config/bashrc.d/bash-preexec.sh" = "~/.config/bashrc.d/bash-preexec.sh"
"dotfiles/bash/.profile" = "~/.profile"

[erdtree.files]
"dotfiles/erdtree/.config/erdtree/.erdtree.toml" = "~/.config/erdtree/.erdtree.toml"

[git.files]
"dotfiles/git/.config/git/config" = "~/.config/git/config"
"dotfiles/git/.config/git/ignore" = "~/.config/git/ignore"
"dotfiles/git/.ssh/allowed_signers" = "~/.ssh/allowed_singers"

[starship.files]
"dotfiles/starship/starship.toml" = "~/.config/starship.toml"
