[alacritty.files]
"dotfiles/alacritty/.config/alacritty/alacritty.toml" = "~/.config/alacritty/alacritty.toml"

[atuin.files]
"dotfiles/atuin/.config/atuin/config.toml" = "~/.config/atuin/config.toml"

[bash.files]
"dotfiles/bash/.bash_profile" = "~/.bash_profile"
"dotfiles/bash/.bashrc" = "~/.bashrc"
"dotfiles/bash/.config/bashrc.d/aliases.sh" = "~/.config/bashrc.d/aliases.sh"
"dotfiles/bash/.config/bashrc.d/bash-preexec.sh" = "~/.config/bashrc.d/bash-preexec.sh"
"dotfiles/bash/.profile" = "~/.profile"

[bat.files]
"dotfiles/bat/.config/bat/config" = "~/.config/bat/config"

[erdtree.files]
"dotfiles/erdtree/.config/erdtree/.erdtree.toml" = "~/.config/erdtree/.erdtree.toml"

[git.files]
"dotfiles/git/.config/git/config" = "~/.config/git/config"
"dotfiles/git/.config/git/ignore" = "~/.config/git/ignore"
"dotfiles/git/.ssh/allowed_signers" = "~/.ssh/allowed_signers"

[gitlab-ci-local.files]
"dotfiles/gitlab-ci-local/.config/.gitlab-ci-local/.env" = "~/.config/.gitlab-ci-local/.env"
"dotfiles/gitlab-ci-local/.config/.gitlab-ci-local/variables.yml" = "~/.config/.gitlab-ci-local/variables.yml"

[jj.files]
"dotfiles/jj/.config/jj/config.toml" = "~/.config/jj/config.toml"

[npm.files]
"dotfiles/npm/.config/npm/npmrc" = "~/.config/npm/npmrc"

[nushell.files]
"dotfiles/nushell/.config/nushell/config.nu" = "~/.config/nushell/config.nu"
"dotfiles/nushell/.config/nushell/env.nu" = "~/.config/nushell/env.nu"
"dotfiles/nushell/.config/nushell/login.nu" = "~/.config/nushell/login.nu"

[nvim.files]
"dotfiles/nvim/.config/nvim/init.lua" = "~/.config/nvim/init.lua"
"dotfiles/nvim/.config/nvim/lazy-lock.json" = "~/.config/nvim/lazy-lock.json"
"dotfiles/nvim/.config/nvim/lua" = "~/.config/nvim/lua"

[spicetify.files]
"dotfiles/spicetify/.config/spicetify/config-xpui.ini" = "~/.config/spicetify/config-xpui.ini"

[starship.files]
"dotfiles/starship/.config/starship.toml" = "~/.config/starship.toml"

[topgrade.files]
"dotfiles/topgrade/.config/topgrade.toml" = "~/.config/topgrade.toml"

[vscodium.files]
"dotfiles/vscodium/.config/VSCodium/User/keybindings.json" = "~/.config/VSCodium/User/keybindings.json"
"dotfiles/vscodium/.config/VSCodium/User/settings.json" = "~/.config/VSCodium/User/settings.json"

[wezterm.files]
"dotfiles/wezterm/.config/wezterm/wezterm.lua" = "~/.config/wezterm/wezterm.lua"

[zellij.files]
"dotfiles/zellij/.config/zellij/config.kdl" = "~/.config/zellij/config.kdl"
"dotfiles/zellij/.config/zellij/layouts/terminal.kdl" = "~/.config/zellij/layouts/terminal.kdl"

[zsh-light.files]
"dotfiles/zsh/.config/zsh/.zshrc" = "~/.config/zsh/.zshrc"
"dotfiles/zsh/.zprofile" = "~/.config/zsh/.zprofile"
"dotfiles/zsh/.zshenv" = "~/.zshenv"

[zsh]
depends = ["zsh-light"]

[zsh.files]
"dotfiles/bash/.profile" = "~/.profile"
"dotfiles/bash/.config/bashrc.d/aliases.sh" = "~/.config/zshrc.d/aliases.zsh"
