[bash.files]
"dotfiles/bash/bashrc" = "~/.bashrc"
"dotfiles/bash/profile" = "~/.profile"
"dotfiles/bash/bash_profile" = "~/.bash_profile"

[git.files]
"dotfiles/git/gitconfig" = "~/.config/git/config"
"dotfiles/git/gitignore" = "~/.config/git/ignore"
"dotfiles/git/allowed_signers" = "~/.ssh/allowed_singers"
