includes = [".dotter/includes/windows.toml"]

packages = [
  "alacritty",
  "bat",
  "eza",
  "fd",
  "git",
  "helix",
  "jujutsu",
  "powershell",
  "ripgrep",
  "starship",
  "yazi",
]

[files]
"powershell/.config/powershell/" = "S:/Documents/PowerShell/"
