includes = [".dotter/includes/windows.toml"]

packages = [
  "alacritty",
  "bat",
  "eza",
  "fd",
  "git",
  "helix",
  "jujutsu",
  "powershell",
  "ripgrep",
  "spicetify",
  "starship",
  "topgrade",
  "wezterm",
  "yazi",
]

[files]
"powershell/.config/powershell/" = "S:/Documents/PowerShell/"

[files."spicetify/.config/spicetify/config-xpui.ini"]
target = "~/AppData/Roaming/spicetify/config-xpui.ini"
type = "template"
append = """
version = 1.2.78.418.gaeeb5ebd
with    = 2.42.5
"""

[variables]
spotify_path = "C:\\Users\\pigeonf\\AppData\\Roaming\\Spotify"
spotify_prefs = "C:\\Users\\pigeonf\\AppData\\Roaming\\Spotify\\prefs"
