[user]
email = "fnoegip@gmail.com"
name = "Jonas Fierlings"

[ui]
default-command = "log"
diff-editor = "diffedit3-ssh"
merge-editor = "vscodium"
paginate = "never"

[git]
push-branch-prefix = "PigeonF/push-"

[signing]
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID+2wAQrbFDe18oFY2Mv6qsUcYWJZPAcsV+Xr4ZHzncL"
sign-all = true

[merge-tools.diffedit3-ssh]
program = "diffedit3"
edit-args = [
  "$left",
  "$right",
  "$output",
  "--port",
  "17376-17380",
  "--no-browser",
]

[merge-tools.vscodium]
program = "codium"
merge-args = ["--wait", "--merge", "$left", "$right", "$base", "$output"]
merge-tool-edits-conflict-markers = true

[aliases]
d = ["diff"]
l = ["log"]
s = ["status"]
